### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by Sylvarithos** [devtopstar0201/next-auth-mongodb#1]
There is no authentication part in the project.
It can be done to get the user name and email from the session.

**Comment by GodricGryffindorK** [comment]
Hi @devtopstar0201 
Follow these steps, and you will get the result.
1. Create a file called ...nextauth.js in pages/api/auth.
2. This file contains the dynamic route handler for NextAuth.js and all your global NextAuth.js configurations.
3. Install the next-auth.js library.
4. Create an api folder in your root app folder.
5. Create an auth folder inside the api folder.
6. Create a [..nextauth] folder inside the auth folder.
7. Create two files named route.ts and options.ts.
8. Insert the following code into the options.ts file:
```
 import type { NextAuthOptions } from 'next-auth'

import GoogleProvider from "next-auth/providers/google"
```
9. Install NextAuth.js.
10. Create an auth.config.ts file.
11. Import the authConfig object into a Middleware file .

Please refer to this URL.
https://next-auth.js.org/getting-started/introduction

**Comment by Sylvarithos** [comment]
Great! thanks.
