### ISSUE TITLE
Deploy vercel issue

### ISSUE THREAD

**Issue by Sylvarithos** [devtopstar0201/next-auth-mongodb#2]
I am going to deploy the Next project to Vercel.
I am using MongoDB for database.
So I am using Atlas Mongodb.
But for integration of Vercel and Atlas, there was a problem.
I want a help

**Comment by GodricGryffindorK** [comment]
Hi @devtopstar0201 
I also had a issue with yours.
I solved with these steps.
Have you prepared these?
1. MongoDB Atlas(sign up for free)
2. A vercel account(sign up for free)
3. nodejs 18+
4. npm and npx

If we look at our Next.js application directory, we'll find an env.local.example file. Let's rename this file to env.local and open it. This file contains one property that we'll need to fill out: MONGODB_URI.

To get our MongoDB URI, in our MongoDB Atlas dashboard:
1. Hit the Connect button.
2. Then, click the Connect to your application button, and here you'll see a string that contains your URI that will look like this:
`mongodb+srv://<USERNAME>:<PASSWORD>@cluster0.<appId>.mongodb.net/<DBNAME>?retryWrites=true&w=majority`

then it will works. Good luck.

Refer this url. https://next-auth.js.org/getting-started/introduction

**Comment by Sylvarithos** [comment]
yes, You are a great dev.
